"""empty message

Revision ID: 2549d017b2bf
Revises: 8be3c45a6a9c
Create Date: 2022-05-28 20:01:50.977021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2549d017b2bf'
down_revision = '8be3c45a6a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('caloriesBurned', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'caloriesBurned')
    # ### end Alembic commands ###
