"""empty message

Revision ID: 77f6e1ede53c
Revises: af6f3d084617
Create Date: 2022-06-11 17:42:25.044186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f6e1ede53c'
down_revision = 'af6f3d084617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('name', sa.Text(), nullable=True))
    op.alter_column('workout', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('run', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('exercise', 'name')
    # ### end Alembic commands ###
