"""empty message

Revision ID: 84e8030385f4
Revises: 77f6e1ede53c
Create Date: 2022-06-14 10:09:12.779290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e8030385f4'
down_revision = '77f6e1ede53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('run', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('workout', sa.Column('caloriesBurned', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'caloriesBurned')
    op.alter_column('run', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercise', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
