"""empty message

Revision ID: 8be3c45a6a9c
Revises: fb35f3b7d633
Create Date: 2022-05-28 20:00:34.494781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be3c45a6a9c'
down_revision = 'fb35f3b7d633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('caloriesBurned', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'caloriesBurned')
    # ### end Alembic commands ###
