"""empty message

Revision ID: af6f3d084617
Revises: b9890feb9e5b
Create Date: 2022-06-11 17:31:51.071063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6f3d084617'
down_revision = 'b9890feb9e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('name', sa.Text(), nullable=True))
    op.alter_column('run', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('run', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('exercise', 'name')
    # ### end Alembic commands ###
