"""empty message

Revision ID: fb35f3b7d633
Revises: 3e7ce5d4ebc9
Create Date: 2022-05-28 19:58:05.065536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb35f3b7d633'
down_revision = '3e7ce5d4ebc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WorkoutExercise')
    op.drop_table('FitnessData')
    op.drop_table('fitness_data')
    op.drop_table('targets')
    op.drop_table('workout_record')
    op.add_column('run', sa.Column('caloriesBurned', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'caloriesBurned')
    op.create_table('workout_record',
    sa.Column('record_id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=True),
    sa.Column('caloriesBurned', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('targets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('caloriesEaten', sa.INTEGER(), nullable=True),
    sa.Column('caloriesBurned', sa.INTEGER(), nullable=True),
    sa.Column('minutesTrained', sa.INTEGER(), nullable=True),
    sa.Column('distanceRan', sa.INTEGER(), nullable=True),
    sa.Column('userId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fitness_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.Column('vo2Max', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.INTEGER(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('userId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FitnessData',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.Column('vo2Max', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.INTEGER(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('userId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WorkoutExercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exerciseId', sa.INTEGER(), nullable=True),
    sa.Column('workoutId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['exerciseId'], ['Exercise.id'], ),
    sa.ForeignKeyConstraint(['workoutId'], ['Workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
